name: elbe
description: a toolkit for simplifying frontend development
version: 0.1.32
homepage: https://robbb.in
repository: https://github.com/RobinNaumann/elbe_flutter

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.2
  device_info_plus: ^9.1.1
  flutter:
    sdk: flutter
  lucide_icons: ^0.257.0
  package_info_plus: ^4.2.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/logo_elbe.png
  fonts:
    - family: Calistoga
      fonts:
        - asset: assets/font/Calistoga-Regular.ttf
    - family: SpaceMono
      fonts:
        - asset: assets/font/space_mono/SpaceMono-Regular.ttf
        - asset: assets/font/space_mono/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/font/space_mono/SpaceMono-Italic.ttf
          style: italic
        - asset: assets/font/space_mono/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic
